# Generated by Django 3.2.4 on 2021-06-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpaypayment', '0002_alter_order_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
